apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: dispatch
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
