apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: dispatch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi

