apiVersion: v1
kind: Service
metadata:
  name: dispatch-web
  namespace: dispatch
spec:
  type: ClusterIP
  selector:
    app: dispatch-web
  ports:
    - name: http
      port: 80
      targetPort: http

